services:
  proxy:
    image: $USER/l2tp-proxy
    build: .
    init: true
    restart: unless-stopped
    # Wait 30s before sending SIGKILL in order to disconnect the IPSec.
    stop_grace_period: 30s
    cap_add:
      - NET_ADMIN
      - SYSLOG
    devices:
      - /dev/ppp
    ports:
      - '127.0.0.1:8118:8118'
      - '[::]:8118:8118'
    secrets:
      - vpn.params
    environment:
      TZ: Asia/Tokyo

secrets:
  vpn.params:
    file: ./vpn.params
